import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import studentRouter from "./student";
import leaderboardRouter from "./leaderboard";
import adminRouter from "./admin";
import teacherRouter from "./teacher";
import teacherAnalyticsRouter from "./teacher-analytics";
import challengesRouter from "./challenges";
import identityRouter from "./identity";
import gamesRouter from "./games";
import chatRouter from "./chat";
import storyRouter from "./story";
import activityLogsRouter from "./activity-logs";
import friendsRouter from "./friends";
import storageRouter from "./storage";
import libraryRouter from "./library";
import readingCoachRouter from "./reading-coach";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(identityRouter);
router.use(studentRouter);
router.use(leaderboardRouter);
router.use(adminRouter);
router.use(teacherRouter);
router.use(teacherAnalyticsRouter);
router.use(challengesRouter);
router.use(gamesRouter);
router.use(chatRouter);
router.use(storyRouter);
router.use(activityLogsRouter);
router.use(friendsRouter);
router.use(storageRouter);
router.use(libraryRouter);
router.use(readingCoachRouter);

export default router;
